_target_: src.models.fine_tuning_sam.sam_ft_module.FTSamLitModule
defaults:
  - net: sam_ft.yaml

criterion_1:
  _target_: src.models.loss.focalloss.FocalLoss
  tag: "focal_loss"

criterion_2:
  _target_: src.models.loss.diceloss.DiceLoss
  tag: "dice_loss"

criterion_3:
  _target_: src.models.loss.iouloss.IoULoss
  tag: "IoU_loss"

compile: True

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0008
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.LambdaLR
  _partial_: true
  # mode: min
  # factor: 0.1
  # patience: 10

warmup_steps: 250
steps: [60000, 86666]
decay_factor: 10